name: GitHub CI

on: [push, pull_request]

jobs:
  ubuntu-build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libevent-dev libseccomp-dev git libsasl2-dev
    - name: Build
      run: |
        gcc --version
        ./autogen.sh
        ./configure --enable-seccomp --enable-tls --enable-sasl --enable-sasl-pwdb
        make -j
    - name: coderrect setup
      run: |
        wget https://public-installer-pkg.s3.us-east-2.amazonaws.com/coderrect-linux-develop.tar.gz
        tar zxf coderrect-linux-develop.tar.gz
        echo "$PWD/coderrect-linux-develop/bin" >> $GITHUB_PATH
        make clean
    - name: coderrect make
      run: coderrect -analyzeAllBinaries make -j
    - name: coderrect check
      run: coderrect -publishResults -report.host=DEFAULT
